# Generated by Django 3.2.7 on 2021-09-09 12:56

import backend.apps.publication.models.article
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.article')),
                ('audio_title', models.CharField(max_length=500)),
                ('audio_author', models.CharField(max_length=300)),
                ('album', models.CharField(blank=True, max_length=300, null=True)),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to=backend.apps.publication.models.article.get_image_upload_path)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('duration', models.CharField(max_length=20)),
            ],
            bases=('publication.article',),
        ),
        migrations.CreateModel(
            name='Fatawi',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.article')),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to=backend.apps.publication.models.article.get_image_upload_path)),
                ('fatawi_pdf', models.FileField(upload_to=backend.apps.publication.models.article.get_pdf_upload_path)),
                ('content', tinymce.models.HTMLField(default=1)),
            ],
            bases=('publication.article',),
        ),
        migrations.CreateModel(
            name='Praycard',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.article')),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to=backend.apps.publication.models.article.get_image_upload_path)),
            ],
            bases=('publication.article',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.article')),
                ('youtube_link', models.CharField(max_length=250)),
            ],
            bases=('publication.article',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='publication.category')),
            ],
            options={
                'verbose_name_plural': 'catgories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.category'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.article')),
                ('book_pdf', models.FileField(upload_to='')),
                ('cover', models.ImageField(blank=True, default='default.png', upload_to=backend.apps.publication.models.article.get_image_upload_path)),
                ('book_audio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.audio')),
            ],
            bases=('publication.article',),
        ),
    ]
