# Generated by Django 3.2.7 on 2021-09-12 09:12

import backend.apps.publication.models.article
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=backend.apps.publication.models.article.get_pdf_upload_path),
        ),
    ]
