# Generated by Django 3.2.7 on 2021-09-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.category')),
            ],
            bases=('publication.category',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.category')),
            ],
            bases=('publication.category',),
        ),
        migrations.AddField(
            model_name='article',
            name='klass',
            field=models.ManyToManyField(related_name='klass', to='publication.Klass'),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, related_name='series', to='publication.Series'),
        ),
    ]
