# Generated by Django 3.2.7 on 2021-09-12 09:15

import backend.apps.publication.models.article
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_audio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=backend.apps.publication.models.article.get_audio_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(upload_to=backend.apps.publication.models.article.get_pdf_upload_path),
        ),
    ]
